apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: bookkeeper-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-02-14T11:49:55Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/version: 0.1.9
    helm.sh/chart: bookkeeper-operator-0.2.4
  name: bookkeeper-operator
  namespace: default
  resourceVersion: "104112025"
  uid: 026e8e13-d8e7-4a5d-8f31-7e64c7202041
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: bookkeeper-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: bookkeeper-operator
        name: bookkeeper-operator
    spec:
      containers:
      - command:
        - bookkeeper-operator
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: bookkeeper-operator
        image: pravega/bookkeeper-operator:0.1.9
        imagePullPolicy: IfNotPresent
        name: bookkeeper-operator
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookkeeper-operator
      serviceAccountName: bookkeeper-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: selfsigned-cert-tls-bk
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-14T11:49:55Z"
    lastUpdateTime: "2025-02-14T11:49:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-14T11:49:55Z"
    lastUpdateTime: "2025-02-14T11:49:55Z"
    message: ReplicaSet "bookkeeper-operator-58b549f7f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
