apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2025-02-14T11:55:39Z"
  generation: 1
  name: pravega-pravega-controller
  namespace: default
  ownerReferences:
  - apiVersion: pravega.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PravegaCluster
    name: pravega
    uid: 653e23f5-2750-44f8-bef5-eb2934aa18bb
  resourceVersion: "104113490"
  uid: bd3d30de-b335-49ca-b0d1-140d755d1cf5
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: pravega-cluster
      component: pravega-controller
      pravega_cluster: pravega
status:
  conditions:
  - lastTransitionTime: "2025-02-14T11:56:19Z"
    message: ""
    observedGeneration: 1
    reason: InsufficientPods
    status: "False"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
