apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2025-02-13T18:20:15Z"
  generation: 1
  labels:
    app: zookeeper
    owner-rv: "106577830"
    release: zookeeper
  name: zookeeper
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: zookeeper
    uid: ce921417-0b1e-4ddb-aabd-acf445da7eb5
  resourceVersion: "106577905"
  uid: df20b83a-b1c2-43ab-9291-d61fa42251fd
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-headless
  template:
    metadata:
      creationTimestamp: null
      generateName: zookeeper
      labels:
        app: zookeeper
        kind: ZookeeperMember
        release: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zookeeper
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - command:
        - /usr/local/bin/zookeeperStart.sh
        env:
        - name: ENVOY_SIDECAR_STATUS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['sidecar.istio.io/status']
        image: pravega/zookeeper:0.2.15
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - zookeeperTeardown.sh
        livenessProbe:
          exec:
            command:
            - zookeeperLive.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: zookeeper
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: quorum
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        - containerPort: 7000
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: admin-server
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - zookeeperReady.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /conf
          name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zookeeper
      serviceAccountName: zookeeper
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: zookeeper-configmap
        name: conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
        release: zookeeper
        uid: ce921417-0b1e-4ddb-aabd-acf445da7eb5
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: zookeeper-67589cf785
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: zookeeper-67589cf785
  updatedReplicas: 3
