apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: zookeeper-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-02-13T18:19:09Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/version: 0.2.15
    helm.sh/chart: zookeeper-operator-0.2.15
  name: zookeeper-operator
  namespace: default
  resourceVersion: "104108780"
  uid: 1613d48b-cd6a-4932-9949-a88647625186
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: zookeeper-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: zookeeper-operator
        name: zookeeper-operator
    spec:
      containers:
      - command:
        - zookeeper-operator
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: zookeeper-operator
        image: pravega/zookeeper-operator:0.2.15
        imagePullPolicy: IfNotPresent
        name: zookeeper-operator
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zookeeper-operator
      serviceAccountName: zookeeper-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-13T18:19:09Z"
    lastUpdateTime: "2025-02-13T18:19:09Z"
    message: ReplicaSet "zookeeper-operator-775468785c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-14T11:31:43Z"
    lastUpdateTime: "2025-02-14T11:31:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
