apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-operator
  name: zookeeper-operator
  namespace: neardata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-operator
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      containers:
        - image: pravega/zookeeper-operator:0.2.15
          imagePullPolicy: IfNotPresent
          name: zookeeper-operator
          ports:
            - containerPort: 6000
              name: metrics
              protocol: TCP
