apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-13T18:20:15Z"
  generateName: zookeeper-
  labels:
    app: zookeeper
    controller-revision-hash: zookeeper-67589cf785
    kind: ZookeeperMember
    release: zookeeper
    statefulset.kubernetes.io/pod-name: zookeeper-0
  name: zookeeper-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: zookeeper
    uid: df20b83a-b1c2-43ab-9291-d61fa42251fd
  resourceVersion: "104108964"
  uid: 789883c8-19ce-40b1-aa1e-e62dd6d53f1d
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - zookeeper
          topologyKey: kubernetes.io/hostname
        weight: 20
  containers:
  - command:
    - /usr/local/bin/zookeeperStart.sh
    env:
    - name: ENVOY_SIDECAR_STATUS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['sidecar.istio.io/status']
    image: pravega/zookeeper:0.2.15
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - zookeeperTeardown.sh
    livenessProbe:
      exec:
        command:
        - zookeeperLive.sh
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: zookeeper
    ports:
    - containerPort: 2181
      name: client
      protocol: TCP
    - containerPort: 2888
      name: quorum
      protocol: TCP
    - containerPort: 3888
      name: leader-election
      protocol: TCP
    - containerPort: 7000
      name: metrics
      protocol: TCP
    - containerPort: 8080
      name: admin-server
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - zookeeperReady.sh
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /conf
      name: conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4ngcc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: zookeeper-0
  nodeName: neardata-2204-work01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: zookeeper
  serviceAccountName: zookeeper
  subdomain: zookeeper-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-zookeeper-0
  - configMap:
      defaultMode: 420
      name: zookeeper-configmap
    name: conf
  - name: kube-api-access-4ngcc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-02-13T18:20:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-02-14T11:32:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-02-14T11:32:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-02-13T18:20:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ebccfd174e1f639d54065a207010821abc7a68ac055ca506cf65d3c249a2a4db
    image: docker.io/pravega/zookeeper:0.2.15
    imageID: docker.io/pravega/zookeeper@sha256:c498ebfb76a66f038075e2fa6148528d74d31ca1664f3257fdf82ee779eec9c8
    lastState:
      terminated:
        containerID: containerd://5d1f23723044ece295b0a0ec3fbb32b89bb60665c1f9147dd0bf57fb4e3235e6
        exitCode: 137
        finishedAt: "2025-02-14T11:26:29Z"
        reason: Error
        startedAt: "2025-02-14T11:25:20Z"
    name: zookeeper
    ready: true
    restartCount: 282
    started: true
    state:
      running:
        startedAt: "2025-02-14T11:32:25Z"
  hostIP: 10.15.2.51
  phase: Running
  podIP: 10.244.1.126
  podIPs:
  - ip: 10.244.1.126
  qosClass: BestEffort
  startTime: "2025-02-13T18:20:17Z"
---
---
