apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: neardata
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-headless
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zookeeper
              topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/local/bin/zookeeperStart.sh
        env:
        - name: ENVOY_SIDECAR_STATUS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['sidecar.istio.io/status']
        image: pravega/zookeeper:0.2.15
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - zookeeperTeardown.sh
        livenessProbe:
          exec:
            command:
            - zookeeperLive.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: zookeeper
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: quorum
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        - containerPort: 7000
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: admin-server
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - zookeeperReady.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /conf
          name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zookeeper
      serviceAccountName: zookeeper
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: zookeeper-configmap
        name: conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
        release: zookeeper
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-13T18:20:15Z"
  labels:
    app: zookeeper
    headless: "true"
    owner-rv: "103954608"
    release: zookeeper
  name: zookeeper-headless
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: zookeeper
    uid: ce921417-0b1e-4ddb-aabd-acf445da7eb5
  resourceVersion: "103954643"
  uid: 277c956a-2253-4583-9b34-27654a47a0ca
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-quorum
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: tcp-leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: tcp-metrics
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: tcp-admin-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-13T18:20:15Z"
  labels:
    app: zookeeper
    headless: "false"
    owner-rv: "103954608"
    release: zookeeper
  name: zookeeper-client
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: zookeeper
    uid: ce921417-0b1e-4ddb-aabd-acf445da7eb5
  resourceVersion: "103954639"
  uid: c46affe7-bfed-45ed-8601-2cecc1da4d95
spec:
  clusterIP: 10.111.173.228
  clusterIPs:
  - 10.111.173.228
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-13T18:20:15Z"
  labels:
    app: zookeeper
    headless: "false"
    owner-rv: "103954608"
    release: zookeeper
  name: zookeeper-admin-server
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: zookeeper
    uid: ce921417-0b1e-4ddb-aabd-acf445da7eb5
  resourceVersion: "103954656"
  uid: caa70553-664d-4e7d-bb8a-c3115410a4bc
spec:
  clusterIP: 10.101.161.171
  clusterIPs:
  - 10.101.161.171
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-admin-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
