apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookkeeper-operator
  namespace: neardata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookkeeper-operator
  template:
    metadata:
      labels:
        name: bookkeeper-operator
    spec:
      containers:
      - image: pravega/bookkeeper-operator:0.1.9
        imagePullPolicy: IfNotPresent
        name: bookkeeper-operator
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
