apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: pravega-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-02-14T11:54:19Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pravega-operator
    app.kubernetes.io/version: 0.5.7
    helm.sh/chart: pravega-operator-0.6.3
  name: pravega-operator
  namespace: default
  resourceVersion: "104113027"
  uid: db640fee-90da-427f-9541-7ae107c4e3ec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: pravega-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: pravega-operator
        name: pravega-operator
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - pravega-operator
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: pravega-operator
        image: pravega/pravega-operator:0.5.7
        imagePullPolicy: IfNotPresent
        name: pravega-operator
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pravega-operator
      serviceAccountName: pravega-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: selfsigned-cert-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-14T11:54:21Z"
    lastUpdateTime: "2025-02-14T11:54:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-14T11:54:19Z"
    lastUpdateTime: "2025-02-14T11:54:21Z"
    message: ReplicaSet "pravega-operator-598c78d84" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
